### ISSUE TITLE
poor performance relative to FlexiJoins in integer case

### ISSUE THREAD

**Issue by ericphanson** [beacon-biosignals/DataFrameIntervals.jl#24]
I have the task of matching individual sample points (integers) into AlignedSpan sample regions. I have found that if I map to raw `Int`s and `UnitRange{Int}`s, I get much better performance with FlexiJoins than using `Interval{Int, Closed, Closed}` with DataFrameIntervals. This problem might be out-of-scope for DataFrameIntervals, but maybe it also indicates a place where perf could be improved.

For my actual task, I am having trouble using FlexiJoins due to compat issues (Flux v0.12 needs ArrayInterface 5, while FlexiJoins 0.1.23 is the latest release, and needs Static 0.7-something, which needs ArrayInterface v6... it's a whole mess). So if DataFrameIntervals could solve this more performantly without needing extra dependencies that introduce compat issues, that would be wonderful. For now I am using DataFrameIntervals despite the perf shortfall to avoid the compat problem.

Here is my MWE.

Versions:
```julia
FlexiJoins v0.1.23
Intervals v1.8.0
DataFrameIntervals v0.1.0
```
on Julia 1.8.2 (ubuntu).

Problem:
```julia
using DataFrames, Intervals, StableRNGs
using DataFrameIntervals, FlexiJoins

N_INTERVALS = 1000
N_POINTS = 10^5

function make_example(n_intervals, n_points)
    rng = StableRNG(123)
    points = [rand(rng, 1:10_000) for _ in 1:n_points]
    L = DataFrame(:point => points)
    transform!(L, :point => ByRow(p -> Interval{Int,Closed,Closed}(p, p)) => :interval)

    indices = map(1:n_intervals) do _
        i = rand(rng, 1:10_000)
        return i:i+100
    end
    R = DataFrame(:indices => indices)
    transform!(R, :indices => ByRow(I -> Interval{Int,Closed,Closed}(first(I), last(I))) => :interval)
    return L, R
end

L, R = make_example(N_INTERVALS, N_POINTS)
@time FlexiJoins.innerjoin((L, R), by_pred(:point, ∈, :indices))
@time interval_join(L, R; on=:interval)
```

The FlexiJoin join takes 0.14 seconds, while the `interval_join` takes 22s, 157x slower.

I originally had `N_INTERVALS = 3000` and `N_POINTS = 10^6`, for which FlexiJoins took 4-5s, and DataFrameIntervals was still running after 15 mins when I cancelled and reduced those values to make the MWE more minimal.

**Comment by haberdashPI** [comment]
This should be addressed when https://github.com/invenia/Intervals.jl/pull/203 closes

**Comment by haberdashPI** [comment]
Just as an update as to the status of this issue: @ericphanson has a PR in `Intervals.jl` that improves the performance of `find_intersections` (which determines performance here) that will suppor the AlignedSpans case. I'll then port that to support all interval types, which should improve performance, in general, for `DataFrameIntervals`.

**Comment by haberdashPI** [comment]
This is addressed by https://github.com/JuliaRegistries/General/pull/85622

**Comment by ericphanson** [comment]
I've realized FlexiJoins doesn't have CI setup (it has github actions script on gitlab which doesn't do anything), so it doesn't fit Beacon's dependency requirements. It also doesn't support the Tables.jl interface which is kind of a non-starter for a tabular join, and its DataFrames support doesn't participate in semver. So I don't think it's a viable alternative to DataFrameIntervals, however it does show these operations could be a lot faster still.

**Comment by haberdashPI** [comment]
Thanks @aplavin for running the benchmark. Super helpful to know! 

I perhaps should have clarified when I closed the issue, that I simply meant the more optimized `find_intersections` method had been implemented. Perhaps I should leave this issue open, given that there is still a pretty big difference in performance.
